## Reference
[1.] [brilliantcode.net](https://www.brilliantcode.net/1045/numpy-tutorial-how-to-print-array/)

## Import NumPy

In [1]:
import numpy as np


1. 建立一個陣列，並給一些初始值！


2. 這邊分別以兩種型別 做舉例

    + 整數: a
    
    + 浮點數: b

In [5]:
# 整數
# array 採用（[]）
a = np.array([1, 2, 3, 4, 5])  

print("整數: a  => {0}".format(a))
print("a.dtype => {0}".format(a.dtype))

整數: a  => [1 2 3 4 5]
a.dtype => int64


In [7]:
# 浮點數
# array 採用（[]）
b = np.array([1.25, 2.25, 3.25, 4.25, 5.25])  

print("浮點數: b => {0}".format(b))
print("b.dtype => {0}".format(b.dtype))

浮點數: b => [1.25 2.25 3.25 4.25 5.25]
b.dtype => float64


## 重要屬性
 - **ndarray.ndim**：NumPy ndarray物件的 **維度**


 - **ndarry.shape**：ndarry物件的每一個維度的 **大小(size)**，回傳資料類別為 **Tuple**


 - **ndarry.size**：
 
    + ndarry物件所組成之 array 的**總元素數量**
    
    + 回應之數值會等於ndarray.shape的每個元素相乘


 - **ndarry.dtype**：ndarray物件內組成元素的型態


 - **ndarray.itemsize**：陣列中每一個元素的大小(Bytes) 
   + ex: int16 => 16/8 = 2 Bytes

 - **ndarry.data**：
 
   + 這是一個存有**實際**陣列元素的**緩衝**
   
   + 通常我們不需要使用這個屬性，因為我們可以使用 **index** 存取這些元素。

In [9]:
c = np.array([(1.9, 1.5, 1.3), (2.9, 2.5, 2.3)], dtype=np.int16)

# ndarray.ndim
print("ndim:{0}".format(c.ndim))
# ndarry.shape
print("shape:{0}".format(c.shape))
# ndarry.size
print("size:{0}".format(c.size))
# ndarry.dtype
print("dtype:{0}".format(c.dtype))
# ndarray.itemsize
print("itemsize:{0}".format(c.itemsize))
# ndarry.data
print("data:{0}".format(c.data))


ndim:2
shape:(2, 3)
size:6
dtype:int16
itemsize:2
data:<memory at 0x1177f1dc8>


# 1 維陣列

 - np.array( [ <陣列元素用**逗號**隔開> ] )：簡易一維陣列
 
 
 - np.arange( 起始值, 結束值, 步幅, 資料型別 )：也是產生一維陣列 
 
 
 #### np.array() 的差別在於arange擁有較大的彈性，而且元素數值是自動化產生！



In [22]:

print("==========\t")
print("  1維陣列\t")
print("==========\n")


print("---陣列元素用逗號隔開--")
a = np.array([6, 5, 4, 3, 2])
print("a => {0}".format(a))
print("---陣列元素從 0~9----")
b = np.arange(10)
print("b => {0}".format(b))
print("--陣列從 0~9, by 1.5-")
c = np.arange(0, 10, 1.5, dtype = np.float64)
print("c => {0}".format(c))

  1維陣列	

---陣列元素用逗號隔開--
a => [6 5 4 3 2]
---陣列元素從 0~9----
b => [0 1 2 3 4 5 6 7 8 9]
--陣列從 0~9, by 1.5-
c => [0.  1.5 3.  4.5 6.  7.5 9. ]


# 2 維陣列
 - 生簡易二維陣列
   + np.array( [[ <Row1陣列元素> ], [ <Row2陣列元素> ]] )



In [24]:
## 2維陣列 2-by-3 array

b2 = np.array([
    [1.1, 1.2, 1.3],
    [2.1, 2.2, 2.3]
])

print("b2 => {0}".format(b2))

b2 => [[1.1 1.2 1.3]
 [2.1 2.2 2.3]]


# 指定陣列型別

 - 產生型別為 int 的陣列
 
 
   + np.array( [[ <Row1陣列元素> ], [ <Row2陣列元素> ]], dtype = np.int16 )：
 
 
   + 主要是 "後面的 dtype" 指定修改

In [30]:
## Assign a particular data type to an array

a2 = np.array([
   [1.9, 1.5, 1.3],[2.9, 2.5, 2.3] 
], dtype = np.int64)  

print("a2 => {0}".format(a2))
print()
print("a2.dtype => {0}".format(a2.dtype))
print()

a2 => [[1 1 1]
 [2 2 2]]

a2.dtype => int64



# 複數陣列 (Complex)


 
 - 用 dtype = complex 指定陣列元素為複數
 
 
 - 把陣列元素用 **複數表示法** 指定就好了：
 
   + 實部+虛部 j
 
 

In [34]:
# case 1
c1 = np.array([(1.1, 1.2, 1.3), (2.1, 2.2, 2.3)], dtype = "complex")

print("c1 => {0}".format(c1))
print()
print("c1.dtype => {0}".format(c1.dtype))

print("\n----------------------\n")

# case 2
c2 = np.array([2.1+6j, 3.2+9j, 4.3+12j])
print("c2 => {0}".format(c2))
print()
print("c2.dtype => {0}".format(c2.dtype))


c1 => [[1.1+0.j 1.2+0.j 1.3+0.j]
 [2.1+0.j 2.2+0.j 2.3+0.j]]

c1.dtype => complex128

----------------------

c2 => [2.1 +6.j 3.2 +9.j 4.3+12.j]

c2.dtype => complex128


#  

# 陣列常用函數

## Zeros
 - np.zeros( (陣列各維度大小用逗號區分) )：
   + 建立全為 0 的陣列，可以小括號定義陣列的各個維度的大小！
 
## Ones
 - np.ones( (陣列各維度大小用逗號區分) )：
   + 建立全為 1 的陣列，可以小括號定義陣列的各個維度的大小！

## Empty
 - np.empty( (陣列各維度大小用逗號區分) )：
   + 用法與 np.zeros 一樣
   
   + 但唯一的差別是 NumPy **不會初始化陣列內元素的初始值**，所以**內容將會是不確定的**。
   
## Linspace
 - np.linspace( 起始值, 結束值, 起始與結束的區間內要產生幾個元素 )：
    + 畫線時還蠻常用到
    + 只要給定 **陣列的區間** (起始值、結束值)，就可以要求在這個區間內產生幾個元素！

In [46]:
print("--------zeros--------")
## zeros
zeros = np.zeros( (3, 5) )
print("zeros =>{0}".format(zeros))

print("\n")


print("\n\n--------Ones--------")
## Ones
ones = np.ones( (3, 5) )
print("ones =>{0}".format(ones))


print("\n")

print("\n\n--------Empty--------")
## Empty
## It means that we want to declare a uninitialized matrix.
empty = np.empty( (2, 5) )
print("empty =>{0}".format(empty))


print("\n")






print("\n\n------Linspace------")
## Linspace
lin = np.linspace(3, 5, 9)          # 起始：3, 終點：5, 此區間[3,5]之間要產生幾個元素：9
print("lin => {0}".format(lin))     
print("lin =>\n {0}".format(lin))   # add \n 表示換行

--------zeros--------
zeros =>[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]




--------Ones--------
ones =>[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]




--------Empty--------
empty =>[[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323 3.5e-323 4.0e-323 4.4e-323]]




------Linspace------
lin => [3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]
lin =>
 [3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]
