## Reference
[1.] [brilliantcode.net](https://www.brilliantcode.net/1045/numpy-tutorial-how-to-print-array/)

# 基本列印 (Basic of Print)


## 下列會給三種陣列預設列印出來的樣子

  - 三種陣列分別是 
     + 1維 
     + 2維 
     + 3維


## 改變維度的函數

 - reshape( )
 
     + 這個函數是用來對 NumPy 的陣列進行**改變維度**的工具
     
     + np.reshape(<欲將陣列改變成維度的大小>)：
          - np.reshape(1, 2)表示要改成1-by-2的矩陣


In [3]:
# The first step
import numpy as np

## 1維陣列

In [13]:
# 1-dim
a1 = np.arange(12)
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## 2維陣列

In [14]:
# 2-dim
a2 = np.arange(12).reshape(3,4)
print(a2)


print("")
print("Keypoint:")
print("1. 先用 np.arange 創造一個 series")
print("2. 再把 reshape(row, column) 接在後面")
print("3. 他的 series 排序方式會從上排到下")



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Keypoint:
1. 先用 np.arange 創造一個 series
2. 再把 np.reshape(row, column) 接在後面
3. 他的 series 排序方式會從上排到下


## 3維陣列

In [20]:
# 3-dim
a3 = np.arange(24).reshape(2,3,4)

print(a3)



print("Example: np.arange(24).reshape(2,3,4)")
print("1. reshape(第一層 block, 第二層 row , 第三層 column)")
print("2. series 排序由內層到外層")


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Example: np.arange(24).reshape(2,3,4)
1. reshape(第一層 block, 第二層 row , 第三層 column)
2. series 排序由內層到外層


# 自訂列印選項


> np.set_printoptions


 - 主要是由以下程式做參數調整。
 
    + 列印選項
    
    + threshold=元素門檻值
    
    + precision=浮點數列印精度
    
    + edgeitems=省略列印內容時要顯示的元素數量
    
    + linewidth=每一行要印出幾個字元
    
    + suppress=是否要抑制顯示小數位
    
    + nanstr=當陣列元素值出現NaN時所顯示的字串
    
    + infstr=當陣列元素值出現inf時所顯示的字串
    
    + sign=控制正負號
    
    + formatter={ 使用lambda函數客製列印陣列元素的格式 } 
    
    
    

 
 - 相關細節請參考以下[連結](https://www.brilliantcode.net/1045/numpy-tutorial-how-to-print-array/)
 