## Reference
[1.] [brilliantcode.net](https://www.brilliantcode.net/1111/numpy-tutorial-shape-manipulation-stack-split-matrices/)






# 形狀操作 (Shape Manipulation)

 - 矩陣 $ M\times N $ 的**形狀 (shape)** 很重要 
 
     + (row, col)
 
 
 - 在進行科學運算時，最常用到矩陣運算
 
 
 
 
 
 - 不過，強大的NumPy中提供了很多**改變矩陣形狀**的功能，可以滿足開發者的需求！



 - **np.reshape(a, b)**：這是最基本的塑形功能，可以直接將陣列重新塑形成 a-by-b 或是更高維度的形狀！
   + (a, b) --> 實際跑出來的結果是 (a, b-1)
 
 
 

In [7]:
import numpy as np

a = np.arange(1,51).reshape(5, 10)

print("a => \n{0}".format(a))

print()

print("a 的形狀： a.shape => {0}".format(a.shape))

a => 
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]

a 的形狀： a.shape => (5, 10)


## np.reshape(a, b, -1)：使用 **-1** 代表這個維度就交給NumPy自動計算！

In [14]:
a = np.arange(1,51).reshape(5,10)


print("case 1:------------")
print("a.reshape(5, 2, 5) => \n{0}".format(a.reshape(5, 2, 5)))

print()

print("case 2:------------")
print("a.reshape(5, 2, -1) => \n{0}".format(a.reshape(5,2,-1)))




print("-------------------")
print("\n會發現 case 1 與 case 2 的結果一樣")

case 1:------------
a.reshape(5, 2, 5) => 
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]]]

case 2:------------
a.reshape(5, 2, -1) => 
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]]]

會發現 case 1 與 case 2 的結果一樣
