## Reference
[1.] [brilliantcode.net](https://www.brilliantcode.net/1093/numpy-1-14-tutorial-04-indexing-slicing-iterating-from-function/)


# 索引

### 索引 (Indexing) 的用途

 - (i)從陣列和矩陣中取值 (常用功能)
 
 
 - (ii)可以取出連續區間
 
 
 - (iii)可以間隔取值
 


 
## 選取連續區間 [a:b]


#### 選取索引值 a 到 b 的資料 x[a:b]


 - a：選取資料的起始索引
 
     + 不指定表示**從頭開始**
     

 - b：選取資料的結束索引+1
 
     + 不指定表示直到**陣列結束**


In [2]:
import numpy as np
x = np.arange(10)**2
print("x => {0}".format(a))
print()
print("x[2:5] => {0}".format(a[2:5]))



# ?????
print("x[2:5] => means that the index is 2,3,4")



print("\n                     Table")
print("--------------------------------------------------")
print("value: 0   1   [4]   [9]    [16]   25   36   49   64   81 \t") # value
print("index: 0   1   (2)   (3)    (4)    5    6    7    8    9 \t") # index
print("--------------------------------------------------")



print("[]: 表示 value\t")
print("(): 表示 index")

NameError: name 'a' is not defined

# 切片 (Slicing)

 - 用途和索引(Indexing) 很像！

 - 若能活用便能加快程式撰寫速度！

## 間隔選取 [::c]
### 以 1 維陣列來說明 x[a:b:c]

 - a：選取資料的起始索引

 - b：選取資料的結束索引+1
 
 - c：選取資料間隔，以索引值可以被此值整除的元素，不指定表示1


### For Example
 - a[3:8:4] 的意思是：從第 3 個元素開始每隔 4 個輸出一次到第 8 個元素為止

In [3]:
a = np.arange(10)**2
print("a => {0}".format(a))

print()

print("a[3:8:4] => \n{0}".format(a[3:8:4]))

print("================================")

a[3:8:4] = 9999

print("a[3:8:4] = 9999 =>> a[3:8:4] => \n{0}".format(a))


a => [ 0  1  4  9 16 25 36 49 64 81]

a[3:8:4] => 
[ 9 49]
a[3:8:4] = 9999 =>> a[3:8:4] => 
[   0    1    4 9999   16   25   36 9999   64   81]


## 倒序 [::-1]

 - 只是單純的把順序反過來，並無數值大小比較


In [4]:
a = np.arange(10)**2
print("a => \n{0}".format(a))
print()
print("a[::-1]) => \n{0}".format(a[::-1]))

a => 
[ 0  1  4  9 16 25 36 49 64 81]

a[::-1]) => 
[81 64 49 36 25 16  9  4  1  0]


* * *

# 迭代

 - 迭代(Iterating)比較熟悉一點，可以說就像foreach一樣的使用方法


In [5]:
# iterating over

a = np.arange(10)**2

print("a => {0}".format(a))

print("=====================================")

for i in a:
    print("a**(0.5) => {0}".format(  np.round(i**(0.5)),0)  )

a => [ 0  1  4  9 16 25 36 49 64 81]
a**(0.5) => 0.0
a**(0.5) => 1.0
a**(0.5) => 2.0
a**(0.5) => 3.0
a**(0.5) => 4.0
a**(0.5) => 5.0
a**(0.5) => 6.0
a**(0.5) => 7.0
a**(0.5) => 8.0
a**(0.5) => 9.0


 - 多維陣列在 **for loop** 中取值時，會以 **第一維度** 為優先！
 
 - 以二維陣列為例：
 
   + 一層 for loop 優先獲取的陣列內容
   
   + 就是第一維度每 row 的內容

In [6]:
b = np.arange(1,41).reshape(5,8)

print("b => \n{0}".format(b))

print("=============================")

# for loop

for row in b:
    # 二維矩陣他會 row by row 由上到下 print 出來
    print(row,"/") 


b => 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]]
[1 2 3 4 5 6 7 8] /
[ 9 10 11 12 13 14 15 16] /
[17 18 19 20 21 22 23 24] /
[25 26 27 28 29 30 31 32] /
[33 34 35 36 37 38 39 40] /


* * *

# 矩陣扁平化 code: XXX.flat


- 直接將 matrix 所有元素 **扁平化**，//依序//取出所有元素！ 

 
 - 此功能必須搭配for-loop, while-loop 使用！
 
 
 - 扁平化就會變成一維陣列 ！
 
 
 
 

In [7]:
b = np.arange(1,13).reshape(3,4)

print("b => \n{0}".format(b))

print("==============================")

for element in b.flat:
    print(element)

b => 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


* * *

# From Function


## What is From Function？

 - 格式是可透過
    + 自定義的函數: **def**
    + 陣列座標值(index) 來建構陣列的方法
 


 - 需要先建立一個函數！


* * *


* * *


## np.fromfunction(函數名稱, 形狀, 資料型別)


 - np.fromfunction(fun_name, shape, dtype)



### For Example: 

#### 下列範例設定的參數分別是：
 - 函數 my_f(row, col)
 
 
 - 用 row*5 + col 作為每一個陣列位置的數值。
 
 
 - 形狀為(5, 5)：就代表要產生5-by-5的矩陣！
 
 
 - 資料產生型別為 int 的矩陣

In [22]:
def my_f(row, col):
    return row*5 + col

b = np.fromfunction(my_f, (5,5), dtype = int)

print()

print("np.fromfunction(my_f, (5,5), dtype = int)".format(b))


print("\n------------ np.fromfunction 解說 ----------------\n")

print("1. 由於一開始設定的是 5*5 的矩陣，my_f 的設計主要在每個 matrix 的 index ")
print("2. (0,0) -> 這個位子代入 my_f(row, col) -> 得到 0*5+0=0"  )
print("3. (2,0) -> 這個位子代入 my_f(row, col) -> 得到 2*5+0=10" )
print("4. (4,3) -> 這個位子代入 my_f(row, col) -> 得到 4*5+3=23" )
print("5. (4,4) -> 這個位子代入 my_f(row, col) -> 得到 4*5+4=24" )

print()



print("-------------- matrix 的index 擷取 ---------------")

print("b[row = 0:5, col = 4]")
print(b[0:5, 4])

print()

print("b[row = all, col = 4]")
print(b[:, 4])



np.fromfunction(my_f, (5,5), dtype = int)

------------ np.fromfunction 解說 ----------------

1. 由於一開始設定的是 5*5 的矩陣，my_f 的設計主要在每個 matrix 的 index 
2. (0,0) -> 這個位子代入 my_f(row, col) -> 得到 0*5+0=0
3. (2,0) -> 這個位子代入 my_f(row, col) -> 得到 2*5+0=10
4. (4,3) -> 這個位子代入 my_f(row, col) -> 得到 4*5+3=23
5. (4,4) -> 這個位子代入 my_f(row, col) -> 得到 4*5+4=24

-------------- matrix 的index 擷取 ---------------
b[row = 0:5, col = 4]
[ 4  9 14 19 24]

b[row = all, col = 4]
[ 4  9 14 19 24]
