## Reference 
[1.] [brilliantcode.net](https://www.brilliantcode.net/1206/numpy-tutorial-indexing-with-boolean-array/)


* * *

# by Elements/ by Cells


### 判斷每一個元素 Elements / Cells

 - 判斷矩陣 a 中每一個位置的數值是否符合我們設定的條件，
 - 再將這個判斷結果儲存成一個布林(boolean)矩陣。
 - 布林矩陣的大小會跟矩陣 a 的大小一致，
 - 可以直接使用這個布林矩陣當作矩陣a的索引值，
 - NumPy會篩選布林矩陣值為True的位置的元素。


For Example at line 3:
1. 直接用 **條件 < 20** 判斷是符合這個條件的元素位置
2. 產生布林矩陣 filter
3. line 11:  取布林矩陣 filter 為 True 的 元素(index) -> 對應到矩陣 a 的位置的**值**更改為 0
4. True 的元素(index)對應到矩陣 a 的位置的**值** 更改為 **0**。


In [5]:
import numpy as np

a = np.arange(25).reshape(5,5)

print("a => \n{0}".format(a))

# 從矩陣a中篩選出數值小於20的index位置，並依此邏輯建立篩選器filter
filter = a < 20

print()

print("filter => \n{0}".format(filter))


a => 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

filter => 
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]]


In [7]:
print('Replace numbers with zero that number is small than 20:')
# 直接將篩選器 (filter) 作為 index 數值
# 將篩選器數值為True對應到a矩陣位置的數值 -> 更改為 0

a[filter] = 0

print("a => \n{0}".format(a))

Replace numbers with zero that number is small than 20:
a => 
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [20 21 22 23 24]]


*** 

# by Rows/ by Columns
### 依據 Rows / Columns 判斷

 - NumPy 可以透過 **布林矩陣** 作為 [篩選條件過濾矩陣內的每一個元素]
 
 
 - 也可以對矩陣選取需要的 Row 或 Column！
 
    + 建立一個布林陣列
       
    + 陣列大小與這次的目標矩陣 a 的 Row or Column 數相等
    
    + 即可依據欲作篩選的維度進行篩選 a[維度1, 維度2, …]。
    
    

In [12]:
a = np.arange(12).reshape(3,4)

print("a => \n{0}".format(a))

print()

b_row = np.array([False,False,True])
b_col = np.array([True, False, True, False])

print("b_row => {0}".format(b_row))
print()
print("b_col => {0}".format(b_col))



a => 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

b_row => [False False  True]

b_col => [ True False  True False]


In [13]:
print('Display rows in matrix "a" that are selected by array "b_row":')
# 使用 b_row 作為矩陣 a 的 row 篩選器，
# 印出 b_row 值為 True 對應到 a 矩陣的數值
print('a[b_row,:]=>\n{0}'.format(a[b_row,:]))

print("\n")

print('')
print('Display columns in matrix "a" that are selected by array "b_col":')
# 使用 b_col 作為矩陣 a 的 col 篩選器
# 印出 _col 值為 True 對應到 a 矩陣的數值
print('a[:,b_col]=>\n{0}'.format(a[:,b_col]))

Display rows in matrix "a" that are selected by array "b_row":
a[b_row,:]=>
[[ 8  9 10 11]]



Display columns in matrix "a" that are selected by array "b_col":
a[:,b_col]=>
[[ 0  2]
 [ 4  6]
 [ 8 10]]
