## Reference
[1.] [brilliantcode.net](https://www.brilliantcode.net/1263/numpy-tutorial-ix-linear-algebra-repeat-stack/)

***

# ix_( ) : 可應用至取 matrix 的 index


### ix_ function 運作模式：

#### 可以 [輸入] 多個陣列 
 
 - Just like:   ix(v1, v2, v3, v4, ...)
   
   
   
   
   
   
 - 以輸入 2 個一維度陣列為例
     + ix(v1, v2)
     + v1: 第一個陣列
     + v2: 第二個陣列
 

 
 - 第一個陣列  v1  作為 [[輸入]]參數 "轉置" 成 **column vector** 回傳。
 
      + **col vector** 就是只有一個 col 的向量 (如下所示):
      
      + e.g., 輸入(1,3) 放在 v1    -> ix_((1,3),:) -> 輸出轉置如下 -> $\begin{bmatrix}
1\\3 
\end{bmatrix}$

 - 第二個陣列  v2  作為 [[輸出]] 以 **row vector**。 
 
      + **row vector** 就是只有一個 row 的向量 (如下所示):

      + e.g., 輸入(2,4) 放在 v2 -> ix_(:,(2,4)) -> 輸出轉置如下 -> $\begin{bmatrix}
2 & 4
\end{bmatrix}$



 - 如果分別將 ix_(v1,v2) 的回傳值 [分別取出]，就可以看出上述的差異。
   

***

   
 - 如果 [直接使用一個變數] 來接收 ix_( ) 的回傳值，會收到一個 **tuple**。
 
 
 
 
 - 這個 **tuple** 則是以 x = ix_(v1, v2) 第一、第二個輸入參數所轉換成的陣列 x -> 依序組合而成的。
 
   + Example: x = ix_(v1, v2),  x is **tuple**.
   
   


In [2]:
# load library
import numpy as np


# create a 5X5 matrix_a

matrix_a = np.arange(0,25).reshape(5,5)


print("matrix_a => \n{0}".format(matrix_a))

matrix_a => 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [14]:

# ix_() will return a tuple 
# what is composed by array [1,3] and array [2,4].
# ix_() 會回傳一個由 [1,3] 和 [2,4] 兩個輸入值而組成的 tuple.



print()
print('np.ix_([1,3],[2,4]) => \n{0}'.format(np.ix_([1,3],[2,4])))

print("\n")
print("直接使用一個變數 x 來接收 ix_( ) 的回傳值，會收到一個 tuple: \n")

x = np.ix_([1,3],[2,4])

print("x = np.ix_([1,3],[2,4]) => \n{0}".format(x))


np.ix_([1,3],[2,4]) => 
(array([[1],
       [3]]), array([[2, 4]]))


直接使用一個變數 x 來接收 ix_( ) 的回傳值，會收到一個 tuple: 

x = np.ix_([1,3],[2,4]) => 
(array([[1],
       [3]]), array([[2, 4]]))


In [24]:
# We can seperate the return value of ix_() as two different array.


print("我們可以分別將 ix_() 的回傳值拆成 [兩個不同的陣列] 取出,\n得到 2 個變數, 分別為 rows 變數與 cols 變數:")
print("----------------------------------------------------------------------------\n")


print('Seperate the return value of ix_(): rows, cols = np.ix_([1,3],[2,4])')

rows, cols = np.ix_([1,3],[2,4])

print('rows, cols = np.ix_([1,3],[2,4])\n\nrows => \n{0}\n\ncols => \n{1}'.format(rows, cols))

我們可以分別將 ix_() 的回傳值拆成 [兩個不同的陣列] 取出,
得到 2 個變數, 分別為 rows 變數與 cols 變數:
----------------------------------------------------------------------------

Seperate the return value of ix_(): rows, cols = np.ix_([1,3],[2,4])
rows, cols = np.ix_([1,3],[2,4])

rows => 
[[1]
 [3]]

cols => 
[[2 4]]


### ix_ 函數把輸入值轉換成這樣，可以用在哪些地方呢？

 - **輸入參數**可以是欲選取矩陣中特定資料的**索引值**，利用 ix_ 對目標矩陣選取需要的資料：
 
 
 
 - 如果我想要選取上述 matrix_a 矩陣中的索引[index] : (1,2)、(1,4)、(3,2)、(3,4) 四筆資料，
 
 
 
 - 因此，對應至矩陣的 row 分別為 (1,3) 以及 column 分別為 (2,4) 的索引值可以分別處理成兩個向量：
  
  + ($\mathrm{v1}$): $\begin{bmatrix} 1 & 3 \end{bmatrix}$
  + ($\mathrm{v2}$): $\begin{bmatrix} 2 & 4 \end{bmatrix}$

 
 
 
 - 最後，就可以直接用 ix_ 的回傳值來選取資料！
    + ix_$( \mathrm{v1}, \mathrm{v2} )$, where $\mathrm{v1} = (1,3)$ and $\mathrm{v2} = (2,4)$.

In [82]:
# The return value of ix_() can divide into two part:
# 1. part composed by the 1st input array, and the 1st part will become a column vector.
# 2. part composed by the 2nd input array, and it will become a row vector.
# Therefore, we can use the return value of ix_() as an index set.


# to get values from a 2-dimension matrix directly.
# ix_()的回傳值分為兩個部分：
# 第一部分由第一個輸入陣列組成, 它會變成一個 column vector. 
# 第二部分由第二個輸入陣列組成, 它會變成一個 row vector. 
# 因此, 我們可以利用ix_()的回傳值形成一組索引集, 直接從一個二維陣列中取值.


print("matrix_a => \n{0}".format(matrix_a))
print()
print('Get values by ix_():')
print()
print('a_ix = matrix_a[ np.ix_([1,3],[2,4]) ] ')
print()
print("np.ix_([1,3],[2,4]) = (1,2),(1,4),(3,2),(3,4)")
print()
a_ix = matrix_a[np.ix_([1,3],[2,4])]
print()
print('a_ix => \n{0}'.format(a_ix))

matrix_a => 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Get values by ix_():

a_ix = matrix_a[ np.ix_([1,3],[2,4]) ] 

np.ix_([1,3],[2,4]) = (1,2),(1,4),(3,2),(3,4)


a_ix => 
[[ 7  9]
 [17 19]]


* * *

# Linear Algebra

## 線性代數常用方法

 - 這邊介紹一些較簡單的線性代數方法：
 
   + 矩陣相乘(matrix product)
   
   + 矩陣內元素相乘(element-by-element multiplication)
   
   + 轉置(transpose)
   
   + 單位矩陣(identify matrix)
   

## 建立 2 個 matrix

In [39]:
## Linear Algebra

x1 = np.array([
    [1,2],[3,4]
], dtype = np.float32).reshape(2,2)

print("x1 is 2X2 matrix => \n{0}\n".format(x1))

x2 = np.array([
    [5,6]
], dtype = np.float32).reshape(2,1)

print("x2 is 2X1 matrix => \n{0}\n".format(x2))


x1 is 2X2 matrix => 
[[1. 2.]
 [3. 4.]]

x2 is 2X1 matrix => 
[[5.]
 [6.]]



## 矩陣相乘 (matrix product)

```
code: np.dot(A,B)
```

In [40]:
# matrix product
# 矩陣相乘
# code: np.dot(A,B)

print("So, x1 X x2 is 2X1 matrix!")
print("np.dot(x1,x2) => \n{0}".format(np.dot(x1,x2)))

So, x1 X x2 is 2X1 matrix!
np.dot(x1,x2) => 
[[17.]
 [39.]]


## 矩陣內**元素**相乘 (element-by-element multiplication)

```
code: x1 * x2
```

In [42]:
# element-by-element multiplication
# 矩陣內**元素**相乘
# code: x1 * x2

print()
print('x1 times x2=>\n{0}'.format(x1*x2))


x1 times x2=>
[[ 5. 10.]
 [18. 24.]]


## 轉置矩陣 (transpose)

```
code: np.transpose(x1)
```

In [43]:
# transpose
# 轉置矩陣
# code: np.transpose(x1)

print()
print('transpose x1=>\n{0}'.format(np.transpose(x1)))


transpose x1=>
[[1. 3.]
 [2. 4.]]


## 單位矩陣 (identity matrix)

In [25]:
#identity matrix
# 單位矩陣
print()
print('identify matrix I=>\n{0}'.format(np.eye(3)))


identify matrix I=>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 重複: Repeat / 堆疊: Stack

### 1. 重複 (repeat) /  重製(tile)
### 2. 堆疊 (hstack, vstack)
***

### np.repeat("a", "repeats", "axis")

 - a：目標矩陣或陣列
 
 
 
 - repeats：輸入值可以是整數、陣列
 
 
 
 - axis：為整數，表示執行重製的軸向
 
 
 
 - 將目標矩陣沿著設定的軸向(第一軸 axis = 0)進行重製。

In [62]:
# 建立一個 3X1 的 matrix: col
col = np.arange(0,3).reshape(3,1)   
# col --> (0,1,2) --> t( (0,1,2) )
print('col=>\n{0}'.format(col))

print("----------------------------------------------")
# Repeat col for 5 times along the 2nd axis.
# 沿著 axis = 1 沿著第 col 軸，重製 col 5次
a = np.repeat(col, 5, axis = 1)
print()
print('repeat col for 5 times at axis = 1 =>\n{0}'.format(a))

col=>
[[0]
 [1]
 [2]]
----------------------------------------------

repeat col for 5 times at axis = 1 =>
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]


In [66]:
# Repeat col for 5 times along the 2nd axis.
# 沿著 axis = 0 表第 row 軸，重製 row 5次
a = np.repeat(col, 5, axis = 0)
print()
print('repeat col for 5 times at axis = 0 => \n{0}'.format(a))


repeat col for 5 times at axis = 0 => 
[[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]]


***
### np.tile("a", "repeats")
 - a：目標矩陣或陣列
 
 
 
 - repeats：參數為一個 **tuple**
    + e.g., tuple: (2,4)
 
 
 
 - 1. 將目標矩陣依 repeats 設定每個維度數值重複執行 n 次
 - 2. 同時沿著 [**各個維度**] 的方向重製。

In [80]:
print("Case 1:")
# Repeat col 2 times along the direction of 1st dimension,
# Repeat col 4 times along the direction of 2nd dimension.
# 1. 沿著第一個維度的方向重複 col 2次
# 2. 沿著第二個維度的方向重複 col 4次.

a1 = np.tile(col, (2,4))
print()
print('repeat col like [2,4] =>\n{0}'.format(a1))

print("\n-----------------------------\n")

print("Case 2:")
# Repeat col 1 times along the direction of 1st dimension,
# Repeat col 2 times along the direction of 2nd dimension.

# 1. 沿著第一個維度的方向重複 col 1次
# 2. 沿著第二個維度的方向重複 col 2次.



a2 = np.tile(col, (1,2))
print()
print('repeat col like [1,2] =>\n{0}'.format(a2))

print("\n-----------------------------\n")

Case 1:

repeat col like [2,4] =>
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]

-----------------------------

Case 2:

repeat col like [1,2] =>
[[0 0]
 [1 1]
 [2 2]]

-----------------------------



***

### np.hstack("array")
 
 
 - 1. 輸入參數內的陣列 [**size必須一致**]
 
 
 - 2. 輸入的陣列沿著 -> [水平方向] -> 合併後 -> 輸出。

In [71]:
# Stack col with horizontal line.
# 將 col 沿著 水平線 堆疊.
print()
print('hstack col=>\n{0}'.format(np.hstack([col, col, col])))


hstack col=>
[[0 0 0]
 [1 1 1]
 [2 2 2]]


***
### np.vstack("array")

 - 1. 輸入參數內的陣列 [**size 必須一致**]


 - 2. 輸入的陣列沿著 -> [垂直方向] -> 合併後 -> 輸出。

In [70]:
# Stack col with vertical line.
# 將 col 沿著 垂直線 堆疊.
print()
print('vstack col=>\n{0}'.format(np.vstack([col, col, col, col])))


vstack col=>
[[0]
 [1]
 [2]
 [0]
 [1]
 [2]
 [0]
 [1]
 [2]
 [0]
 [1]
 [2]]
